# Generated by Django 4.1.13 on 2024-06-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortlistedCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=36)),
                ("resume_id", models.CharField(max_length=24)),
                ("score", models.CharField(max_length=10)),
                ("explanation", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShortlistingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=36)),
                ("num_candidates", models.IntegerField()),
            ],
        ),
    ]
